### PR TITLE
Fix the error of calling small_cnn

### PR DESCRIPTION
**Pull request by ghost**
Caused by uncommitted definition of  small_cnn()

### CODE REVIEW

**Comment by ghost** [comment]
@D0048 ,I have fixed it yet.

**Comment by D0048** [comment]
What's your graphic memory usage during run? My 2g graphic memory is definitely not enough now...

**Comment by ghost** [comment]
@D0048, since the model has been changed, it will take much less graphic memory.
The information like this:
``` 
2017-11-16 19:34:48.963928: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.81GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
 ```
doesn't important, you can ignore it.

**Comment by D0048** [comment]
Since I am getting OOMs like this:
<pre>
2017-11-16 21:05:31.914727: I tensorflow/core/common_runtime/bfc_allocator.cc:685] Stats: 
Limit:                  1043988480
InUse:                  1031679232
MaxInUse:               1038011648
NumAllocs:                     104
MaxAllocSize:            472514560

2017-11-16 21:05:31.914737: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ********************xxxxxxxxx****************xxxxxxxxx*********************************xxxxxxxxxxxxx
2017-11-16 21:05:31.914750: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[5000,64,16,16]
</pre>

I am pretty sure this version takes considerably more graphic memory than the last one. Could you maybe run `nvidia-smi` during training and check if my assertion holds?

**Comment by ghost** [comment]
@D0048 
You can change the code as follows(in ``main()``):
```python
                # Print the accuracy
                train_accuracy = 0
                for index in range(500): #<==============make this number bigger
                    accuracy_batch = mnist.test.next_batch(20)#<==============and reduce this
                    train_accuracy += accuracy.eval(feed_dict={
                        x: accuracy_batch[0],
                            y_: accuracy_batch[1], keep_prob: 1.0})
                print(
                    '%g, %g, %g' %
                    (i / 1000, train_accuracy / 500, (time.clock() - t0)))#<==============It is also needed to be changed here
```
That will work.
It is maybe caused by the bigger size of the input of``small_cnn()``.

**Comment by D0048** [comment]
Already tried batch_size 1 earlier yesterday. The OOM still occurred. Kinda wondering what's the minimum requirement.

**Pull request merged**
